[package]
name = "directory-watcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
pathdiff="0.2.1"
postgres-native-tls = "0.5.0"
native-tls = "0.2.7"
jsonschema="0.15.0"
serde = { version = "1.0.133", features=["derive"] }
serde_json = "1.0.74"
uuid = { version = "0.8.2", features=["v4", "serde"] }
tokio = { version = "1.15.0", features=["full"] }
tokio-postgres = { version = "0.7.5", features = ["with-time-0_3"] }
thiserror = "1.0.26"
tracing="0.1.29"
tracing-subscriber = "0.3.8"
async-walkdir="0.2.0"
futures-lite = "1.12.0"
async-trait = "0.1.52"
tempfile="3.2.0"
time = { version = "0.3.5", features=["local-offset", "parsing", "serde", "formatting"] }

platform = { path = "../../libraries/rust/platform" }
events = { path = "../../libraries/rust/events" }