[package]
name = "directory-watcher"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
lapin = "1.7.1"
pathdiff="0.2.0"
postgres = { version = "0.19.1", features = ["with-chrono-0_4"] }
postgres-native-tls = "0.5.0"
native-tls = "0.2.7"
chrono="0.4.19"