[package]
name = "directory-watcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
pathdiff="0.2.1"
postgres-native-tls = "0.5.0"
native-tls = "0.2.7"
chrono = { version = "0.4.19", features = ["serde"] }
jsonschema="0.13.2"
serde="1.0.130"
serde_json = "1.0.72"
uuid = { version = "0.8.2", features=["serde", "v4"] }
tokio = { version = "1.14.0", features=["full"] }
tokio-postgres = { version = "0.7.5", features = ["with-chrono-0_4"] }
thiserror = "1.0.26"
tracing="0.1.29"
tracing-subscriber = "0.3.2"
async-walkdir="0.2.0"
futures-lite = "1.12.0"
async-trait = "0.1.51"
tempdir="0.3.7"

platform = { path = "../../libraries/rust/platform" }