[package]
name = "directory-watcher"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
lapin = "1.7.1"
pathdiff="0.2.0"
postgres-native-tls = "0.5.0"
native-tls = "0.2.7"
chrono = { version = "0.4.19", features = ["serde"] }
jsonschema="0.12.1"
serde="1.0.129"
serde_json = "1.0.66"
uuid = { version = "0.8.2", features=["serde", "v4"] }
tokio = { version = "1.10.0", features=["full"] }
tokio-amqp = "1.0.0"
tokio-postgres = { version = "0.7.2", features = ["with-chrono-0_4"] }
thiserror = "1.0.26"
tracing="0.1.26"
tracing-subscriber = "0.2.19"