version: 2
updates:
  - package-ecosystem: "composer"
    directory: "services/events/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "libraries/build"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "services/directory-watcher/"
    schedule:
      interval: "daily"