version: 2
updates:
  - package-ecosystem: "composer"
    directory: "services/events/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "services/events/tools/psalm"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "services/events/tools/easy-coding-standard"
    schedule:
      interval: "daily"
