version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "services/events/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "tools/build/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "tools/dependabot-config-checker/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "tools/commit-verifier/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "tools/machine-info/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "services/directory-watcher/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "libraries/rust/platform/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "libraries/php/coding-standard/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "services/directory-watcher/docker/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "services/events/docker/"
    schedule:
      interval: "daily"