apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: ap-directory-watcher
  namespace: default
spec:
  teamId: "ap"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    ap:
      - superuser
      - createdb
    directory_watcher: []
  databases:
    directory_watcher: ap  # dbname: owner
  postgresql:
    version: "13"