kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-events"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 1
  enableConnectionPooler: true
  volume:
    size: "10Gi"
  users:
    events-svc: []
  databases:
    events: events-svc
  allowedSourceRanges:
  # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi