apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: ap-events
  namespace: default
spec:
  teamId: "ap"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    ap:
      - superuser
      - createdb
    events: []
  databases:
    events: ap  # dbname: owner
  postgresql:
    version: "14"