[package]
name = "rpc-support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.18.1", features = ["full"] }
tracing = "0.1.34"
dashmap = "5.2.0"
thiserror = "1.0.30"
platform={path="../platform"}

[build-dependencies]
