[package]
name = "platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror="1.0.30"
tokio = { version = "1.15.0", features=["full"] }
jsonschema="0.13.3"
async-trait = "0.1.51"
serde = { version = "1.0.132", features=["derive"] }
tracing="0.1.26"
serde_json = "1.0.74"
jsonpath-rust = "0.1.4"

events = { path = "../events" }