[package]
name = "platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror="1.0.30"
tokio = { version = "1.18.1", features=["full"] }
async-trait = "0.1.52"
serde = { version = "1.0.136", features=["derive"] }
tracing="0.1.34"
serde_json = "1.0.78"
jsonpath-rust = "0.1.4"

events = { path = "../events" }