apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-directory-watcher
spec:
  template:
    metadata:
      labels:
        app: svc-directory-watcher
    spec:
      initContainers:
        - name: migrations
          image: automation-platform-svc-migrations:610fda30ecce1860524671
      containers:
        - name: app
          image: automation-platform-svc-directory-watcher:610fda30ecce1860524671