[package]
name = "svc-music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
music = { path = "../../libraries/rust/music" }
rpc-support = { path = "../../libraries/rust/rpc-support" }
tokio={ version = "1.19.1", features = ["full"] }
async-trait = "0.1.56"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
futures-core = "0.3.21"
tokio-util = { version = "0.7.2", features=["full"] }
async-std = "1.11.0"
base64 = "0.13.0"
