[package]
name = "events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
tracing="0.1.26"
tracing-subscriber = "0.3.2"
serde = { version = "1.0.130", features=["derive"] }
serde_json="1.0.72"
tokio-postgres = { version = "0.7.5", features=["with-uuid-0_8", "with-time-0_3", "with-serde_json-1"] }
uuid = { version = "0.8.2", features=["v4"] }
postgres-native-tls="0.5.0"
native-tls="0.2.8"
thiserror = "1.0.30"
jsonschema="0.13.2"
time = { version = "0.3.5", features=["local-offset", "parsing", "serde", "formatting"] }

platform = { path = "../../libraries/rust/platform" }