[package]
name = "events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
tracing="0.1.26"
tracing-subscriber = "0.2.19"
serde = { version = "1.0.130", features=["derive"] }
serde_json="1.0.68"
tokio-postgres = { version = "0.7.3", features=["with-uuid-0_8", "with-chrono-0_4", "with-serde_json-1"] }
uuid = { version = "0.8.2", features=["v4"] }
chrono="0.4.19"
postgres-native-tls="0.5.0"
native-tls="0.2.8"
thiserror = "1.0.30"
jsonschema="0.12.1"

platform = { path = "../../libraries/rust/platform" }