[package]
name = "svc-events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
tracing="0.1.34"
tracing-subscriber = "0.3.11"
serde = { version = "1.0.133", features=["derive"] }
serde_json="1.0.74"
tokio-postgres = { version = "0.7.5", features=["with-uuid-0_8", "with-time-0_3", "with-serde_json-1"] }
uuid = { version = "1.0.0", features=["v4"] }
postgres-native-tls="0.5.0"
native-tls="0.2.10"
thiserror = "1.0.31"
time = { version = "0.3.9", features=["local-offset", "parsing", "serde", "formatting"] }

platform = { path = "../../libraries/rust/platform" }
events = { path = "../../libraries/rust/events" }