[package]
name = "events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.73"
uuid = { version = "1.0.0-alpha.1", features=["v4", "serde"] }

[build-dependencies]
event-compiler={path="../../../tools/event-compiler"}