[package]
name = "events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.78"
uuid = { version = "0.8.2", features=["v4", "serde"] }

[build-dependencies]
message-compiler={path= "../../../tools/message-compiler" }