apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-music
  labels:
    app: svc-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-music
  template:
    metadata:
      labels:
        app: svc-music
    spec:
      containers:
        - name: app
          image: automation-platform-svc-music:latest # todo find out how to handle this for prod
          imagePullPolicy: Never # todo this will of course break in prod
      volumes: []