name: build
on: [push]
jobs:
    build-dev:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

            - uses: actions-rs/toolchain@v1
              with:
                toolchain: nightly

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Cache Docker layers
                uses: actions/cache@v2
                with:
                path: /tmp/.buildx-cache
                key: ${{ runner.os }}-buildx-${{ github.sha }}
                restore-keys: |
                    ${{ runner.os }}-buildx-

            - uses: actions/cache@v2
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    **/target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.0'
                tools: composer

            - name: Get composer cache directory
              working-directory: tools/build/
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/composer.json') }}
                restore-keys: ${{ runner.os }}-composer-

            - run: cargo udeps --version || cargo +nightly install cargo-udeps

            - working-directory: tools/build/
              run: composer install

            - run: php tools/build/bin/build.php build-dev
            -
                # Temp fix
                # https://github.com/docker/build-push-action/issues/252
                # https://github.com/moby/buildkit/issues/1896
                name: Move cache
                run: |
                rm -rf /tmp/.buildx-cache
                mv /tmp/.buildx-cache-new /tmp/.buildx-cache
