name: build
on: [push]
jobs:
    build-dev:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                default: true

            - uses: actions-rs/toolchain@v1
              with:
                toolchain: nightly
                default: false

            - uses: actions/cache@v2
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    **/target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-cargo-

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.1'
                tools: composer, composer-require-checker, composer-unused

            - name: Get composer cache directory
              working-directory: tools/build/
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/composer.json') }}
                restore-keys: ${{ runner.os }}-composer-

            - run: cargo udeps --version || cargo +nightly install cargo-udeps
            - run: cargo audit --version || cargo install cargo-audit

            - working-directory: tools/dependabot-config-checker/
              run: composer install

            - working-directory: tools/dependabot-config-checker/
              run: php bin/check.php

            - working-directory: tools/build/
              run: composer install

            - working-directory: tools/machine-info
              run: cargo build --release

            - run: php tools/build/bin/build.php --environment=github-actions build